# 1. PyTorch 실습

## 1-1. Tensor 생성 및 초기화

이미지의 픽셀, 정답 레이블, 모델의 가중치는 숫자로 표현됩니다. PyTorch는 이 데이터를 Tensor로 다루며, GPU 계산과 기울기 계산에도 같은 자료형을 사용합니다.

아래 예제는 **공간 확보 → 균등분포에서 생성 → 정규분포에서 생성 → 직접 값 지정** 순서입니다. `empty`는 값을 초기화하지 않고 공간만 만듭니다. `rand`는 0 이상 1 미만에서 값을 고르게 뽑고, `randn`은 평균 0·표준편차 1인 정규분포에서 값을 뽑습니다.

각 무작위 예제에서는 생성 결과와 평균·표준편차를 함께 확인합니다. 평균은 값의 중심, 표준편차는 퍼짐의 정도입니다. 원소가 15개뿐이므로 표본의 통계량은 분포의 기준과 다를 수 있습니다. 직접 값을 지정하는 마지막 예제는 데이터를 이미 가지고 있을 때 사용하는 방식입니다.

In [12]:
import torch
import numpy as np

In [13]:
# 1. 저장 공간만 생성: 값을 초기화하지 않은 상태
x = torch.empty(5, 3)
print(x)

tensor([[2.3011e-40, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.5080e+21, 7.4410e+34],
        [1.1747e-14, 0.0000e+00, 2.0572e+26],
        [1.1446e+24, 9.1042e-12, 1.1028e+21],
        [7.2065e+31, 0.0000e+00, 0.0000e+00]])


In [14]:
# 2. 0 이상 1 미만의 균등분포에서 무작위 값 생성
x = torch.rand(5, 3)
print(x)
print("평균:", x.mean().item())
print("표준편차:", x.std().item())

tensor([[0.8550, 0.3100, 0.0499],
        [0.2232, 0.3562, 0.1205],
        [0.5158, 0.7315, 0.7892],
        [0.2231, 0.6201, 0.8801],
        [0.4251, 0.7111, 0.0613]])
평균: 0.45814353227615356
표준편차: 0.2922193706035614


In [15]:
# 3. 평균 0, 표준편차 1인 정규분포에서 무작위 값 생성
x = torch.randn(5, 3)
print(x)
print("평균:", x.mean().item())
print("표준편차:", x.std().item())

tensor([[ 1.1475, -0.7769,  0.6069],
        [ 0.8140, -0.1183, -1.1209],
        [-2.6555,  0.2472,  0.4483],
        [-0.3165,  0.7278,  0.3948],
        [ 0.7467, -0.2395, -0.5096]])
평균: -0.040270011872053146
표준편차: 0.9699561595916748


In [16]:
# 4. 직접 지정한 값으로 생성
x = torch.tensor([[1.2, 4.5], [1, 2]])
print(x)

tensor([[1.2000, 4.5000],
        [1.0000, 2.0000]])


In [ ]:
# 연습 문제: 0 이상 1 미만의 무작위 값으로 4행 3열 Tensor를 만드세요.
practice_tensor = None  # TODO: 직접 코드를 작성하세요.

print(practice_tensor)
print(practice_tensor.shape)

## 1-2. Tensor 형태 확인과 변환

### 모델 입력에 맞게 형태 바꾸기

모델에 데이터를 넣을 때는 숫자 개수뿐 아니라 묶여 있는 형태도 중요합니다. MLP에 이미지를 넣을 때 픽셀을 펼쳤던 것처럼, RNN에도 읽는 순서에 맞춰 입력 형태를 구성해야 합니다.

먼저 `size()`로 형태를 확인하고, `reshape`로 12개 원소를 `[3, 4]`에서 `[4, 3]`과 `[6, 2]`로 재배치합니다. `-1`은 나머지 차원을 기준으로 자동 계산하라는 뜻입니다. 원소 수와 순서는 유지되며, 행과 열을 서로 교환하는 전치와는 다릅니다.

In [17]:
# Size 확인
x = torch.randn(3,4)
print(x)
print("x size : ", x.size())

tensor([[-0.7991,  0.6483, -0.1136,  0.1705],
        [ 1.4048, -0.7033, -0.8061, -0.3301],
        [ 0.2126, -1.3715, -0.7260, -0.5888]])
x size :  torch.Size([3, 4])


In [18]:
# Resize - "reshape" : any tensor
x = torch.rand(3,4)
y = x.reshape(4,3)
z = x.reshape(-1, 2)
print(x, x.size(), "\n", y, y.size(), "\n", z, z.size())

tensor([[0.1558, 0.4633, 0.0507, 0.2956],
        [0.8089, 0.2336, 0.7242, 0.1700],
        [0.8325, 0.3056, 0.3930, 0.9500]]) torch.Size([3, 4]) 
 tensor([[0.1558, 0.4633, 0.0507],
        [0.2956, 0.8089, 0.2336],
        [0.7242, 0.1700, 0.8325],
        [0.3056, 0.3930, 0.9500]]) torch.Size([4, 3]) 
 tensor([[0.1558, 0.4633],
        [0.0507, 0.2956],
        [0.8089, 0.2336],
        [0.7242, 0.1700],
        [0.8325, 0.3056],
        [0.3930, 0.9500]]) torch.Size([6, 2])


In [ ]:
# 연습 문제: x를 2행 6열로 바꾸세요.
x = torch.rand(3, 4)
practice_reshape = None  # TODO: reshape를 사용하세요.

print(practice_reshape)
print(practice_reshape.size())

### NumPy와 Tensor 사이에서 데이터 전달하기

데이터 준비와 분석에 NumPy 배열을 사용하고, 모델 입력에는 Tensor를 사용할 수 있습니다. 아래 두 예제는 같은 숫자를 두 자료형 사이에서 변환합니다. `.numpy()`는 CPU Tensor를 NumPy 배열로, `torch.from_numpy()`는 NumPy 배열을 Tensor로 바꿉니다.

이 변환은 메모리를 공유하므로 한쪽 원소를 바꾸면 다른 쪽에도 반영될 수 있습니다. 자료형도 확인할 수 있습니다. 아래 `torch.ones`는 기본적으로 `float32`, `np.ones`는 `float64`를 사용하며 NumPy에서 변환한 Tensor는 그 자료형을 이어받습니다.

In [19]:
# Tensor → NumPy
x = torch.ones(5)
y = x.numpy()
print(x, type(x))
print(y, type(y))

# NumPy → Tensor
x = np.ones(5)
y = torch.from_numpy(x)
print(x, type(x))
print(y, type(y))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


## 1-3. GPU에서 계산하기

학습에서는 많은 숫자를 반복해서 계산합니다. GPU는 이런 계산을 병렬로 처리하는 데 사용합니다. 아래에서는 CPU에 만든 텐서를 GPU로 옮기고, 출력에 표시되는 장치를 비교합니다.

`.to(...)`는 데이터를 지정한 장치로 옮기는 코드입니다. `cuda:0`은 첫 번째 CUDA GPU를 뜻하므로, 이 셀을 실행하려면 GPU를 사용할 수 있어야 합니다. 모델 학습에서는 입력만 옮기는 것이 아니라 모델의 가중치도 같은 장치에 두어야 합니다.

In [20]:
x = torch.ones(5)
y = x.to(device="cuda:0") #런타임 연결 gpu로 설정
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.], device='cuda:0')


## 1-4. Autograd로 기울기 계산하기

MLP와 CNN에서 손실을 계산한 뒤 역전파로 가중치를 수정하는 과정은 RNN에서도 같습니다. PyTorch는 계산 과정을 기록해 두었다가, 결과가 각 입력 값의 변화에 얼마나 영향을 받는지 계산합니다. 이 값이 기울기이고, 이 기능을 Autograd라고 합니다.

아래는 모델 대신 간단한 수식으로 그 과정을 확인하는 예제입니다. 네 숫자 각각에 `3(x+2)²`를 계산하고 평균을 구합니다. `requires_grad=True`는 입력 `x`에 대한 기울기를 구하도록 지정합니다. 평균값에 `backward()`를 호출하면 계산 결과가 `x.grad`에 저장됩니다.

출력된 기울기는 각 입력을 조금 바꿀 때 평균값이 얼마나 변하는지를 나타냅니다. 이 셀에서는 기울기만 계산하며 입력 값은 그대로입니다. 실제 학습에서는 optimizer가 이 기울기를 이용해 모델의 가중치를 업데이트합니다.

In [21]:
x = torch.tensor(([1., 2.], [3., 4.]), requires_grad=True)
print(x)
y = (x+2) **2 *3
print(y)

out = y.mean()
print(out)

out.backward()
print(x.grad)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(64.5000, grad_fn=<MeanBackward0>)
tensor([[4.5000, 6.0000],
        [7.5000, 9.0000]])


## 1-5. 예측부터 가중치 업데이트까지

앞에서는 수식의 기울기만 계산했습니다. 이번에는 `y = 2x`라는 관계를 작은 모델이 학습하도록 만듭니다. 모델은 **예측 = 가중치 × 입력 + 편향**으로 계산하고, 가중치와 편향을 모두 0에서 시작합니다.

모델의 예측과 정답을 비교해 손실을 계산한 뒤, 이전 기울기를 지우고 현재 기울기를 구해 가중치를 업데이트합니다. **예측 → 손실 → 기울기 초기화 → 기울기 계산 → 업데이트**는 뒤의 LSTM·GRU에서도 같은 흐름입니다.

여기서는 숫자값을 예측하는 회귀 문제이므로 `MSELoss`를 사용합니다. 뒤의 숫자·감정 분류에서는 문제에 맞는 다른 손실 함수를 사용합니다. 학습률을 고정하고 업데이트 횟수를 1·10·30으로 바꿔 최종 손실과 예측값을 비교해 보세요.

In [22]:
import torch.nn as nn

toy_lr = 0.5
toy_steps = 30
toy_x = torch.tensor([[0.0], [1.0], [2.0], [3.0]])
toy_y = 2 * toy_x

# 예측 = 가중치 × 입력 + 편향
toy_model = nn.Linear(1, 1)
with torch.no_grad():
    toy_model.weight.zero_()
    toy_model.bias.zero_()
toy_criterion = nn.MSELoss()
toy_optimizer = torch.optim.SGD(toy_model.parameters(), lr=toy_lr)

with torch.no_grad():
    initial_loss = toy_criterion(toy_model(toy_x), toy_y).item()

toy_model.train()
for step in range(toy_steps):
    prediction = toy_model(toy_x)  # 현재 가중치로 예측
    loss = toy_criterion(prediction, toy_y)  # 정답과 비교해 손실 계산
    toy_optimizer.zero_grad()  # 이전 기울기 초기화
    loss.backward()  # 현재 손실의 기울기 계산
    toy_optimizer.step()  # 가중치와 편향 업데이트

toy_model.eval()
with torch.no_grad():
    final_prediction = toy_model(toy_x)
    final_loss = toy_criterion(final_prediction, toy_y).item()
print("정답:", toy_y.squeeze(1).tolist())
print("최종 예측:", final_prediction.squeeze(1).tolist())
print("처음 손실:", initial_loss, "최종 손실:", final_loss)
print("가중치:", toy_model.weight.item(), "편향:", toy_model.bias.item())

정답: [0.0, 2.0, 4.0, 6.0]
최종 예측: [-1123089924489216.0, -3520933658624000.0, -5918777392758784.0, -8316621126893568.0]
처음 손실: 14.0 최종 손실: 2.946410448955921e+31
가중치: -2397843734134784.0 편향: -1123089924489216.0


TODO: 위 코드의 toy_lr(학습률)과 toy_steps(업데이트 횟수)를 조절해 학습이 수렴하도록 수정하세요.

설정을 바꾼 뒤 위 코드 전체를 다시 실행하세요.

최종 손실이 0에 가까워지고, 예측이 정답 [0, 2, 4, 6]에 가까워지는지 확인하세요.